### ISSUE TITLE
babel presets in dependencies

### ISSUE THREAD

**Issue by mschipperheyn** [laurenskling/keystone-with-react-engine#2]
Shouldn't the babel presets be in dev dependencies?

**Comment by laurenskling** [comment]
Well, since i'm using the babel presets in `preprocessor.js`, which is actually run by node, it's production code, not dev code.

**Comment by atodorovAddison** [comment]
HI,

I'm having trouble running it.

npm start

> keystone-react-example@1.0.0 start /Users/atodorov/Desktop/Projects/keystone-with-react-engine
> webpack && node preprocessor.js

Hash: 29b056c3fbd791f95e7e
Version: webpack 1.14.0
Time: 2555ms
        Asset     Size  Chunks             Chunk Names
    bundle.js   966 kB       0  [emitted]  main
bundle.js.map  1.13 MB       0  [emitted]  main
 [288] ./templates/views ^\.\/.*$ 188 bytes {0} [built]
    + 291 hidden modules
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.config (/Users/atodorov/Desktop/Projects/keystone-with-react-engine/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/Users/atodorov/Desktop/Projects/keystone-with-react-engine/keystone.js:3:19)
    at Module._compile (module.js:570:32)
    at loader (/Users/atodorov/Desktop/Projects/keystone-with-react-engine/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/atodorov/Desktop/Projects/keystone-with-react-engine/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }

KeystoneJS Configuration Error:

Please provide a `cookie secret` value for session encryption.

**Comment by laurenskling** [comment]
The project assumes you have a `.env` file in the root. This is your local settings.

**Comment by atodorovAddison** [comment]
I make it running.
Now I'm trying to explore the code.
I can't see admin folder.
Is your version synced with the new beta?

**Comment by atodorovAddison** [comment]
What about admin folder?

**Comment by laurenskling** [comment]
What admin folder? This project is running the @next (4.0.0-beta) react version of Keystone

**Comment by atodorovAddison** [comment]
Hi,

When I go to ;

https://github.com/keystonejs/keystone

The repository  is  "version": "4.0.0-beta.5",
It has admin and lib folders

What’re they for?

**Comment by laurenskling** [comment]
Those are folders of Keystone. In my project, they would live in node_modules/keystone/...

**Comment by laurenskling** [comment]
I'm closing this because the original question is solved.
